/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlbh.view;

import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import qlbh.dao.HangHoaDAO;
import qlbh.model.HangHoa;

/**
 *
 * @author DELL
 */
public class HangHoaJPanel extends javax.swing.JPanel {

    DefaultTableModel dtm = new DefaultTableModel();
    /**
     * Creates new form HangHoaJPanel
     */
    public HangHoaJPanel() {
        initComponents();
        
        String []tieuDe = {"Mã Hàng Hóa", "Tên Hàng Hóa", "Mã Loại", "Số Lượng", "Đơn Vị Tính", "Giá"};
        dtm.setColumnIdentifiers(tieuDe);
        BangDSHH.setModel(dtm);
        
        Disabled();
        hienThi();
    }
    
    private void Disabled(){
        txtDVT.setEnabled(false);
        txtGia.setEnabled(false);
        txtMaHH.setEnabled(false);
        txtMaLoai.setEnabled(false);
        txtSoLuong.setEnabled(false);
        txtTenHH.setEnabled(false);
        btCapNhat.setEnabled(false);
        btLuu.setEnabled(false);
    }
    
    public void hienThi() {
        ArrayList<HangHoa> dsHH = HangHoaDAO.layDanhSachHangHoa();
        dtm.setRowCount(0);
        for(HangHoa hh:dsHH){
            Vector<Object> vec = new Vector<Object>();
            vec.add(hh.getMaHH());
            vec.add(hh.getTenHH());
            vec.add(hh.getMaLoai());
            vec.add(hh.getSoLuong());
            vec.add(hh.getdVT());
            vec.add(hh.getGia());
            dtm.addRow(vec);
    }
        BangDSHH.setModel(dtm);
}
    
    public void hienThiTK(){
        String maHH = txtSearch.getText();
        HangHoaDAO.timKiemHangHoaTheoMaLoai(maHH);
        ArrayList<HangHoa> dsHH = HangHoaDAO.timKiemHangHoaTheoMaLoai(maHH);
        dtm.setRowCount(0);
        for(HangHoa hh:dsHH){
            Vector<Object> vec = new Vector<Object>();
            vec.add(hh.getMaHH());
            vec.add(hh.getTenHH());
            vec.add(hh.getMaLoai());
            vec.add(hh.getSoLuong());
            vec.add(hh.getdVT());
            vec.add(hh.getGia());
            dtm.addRow(vec);
    }
        BangDSHH.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        lbTenHH = new javax.swing.JLabel();
        lbSoLuong = new javax.swing.JLabel();
        lbDVT = new javax.swing.JLabel();
        lbGia = new javax.swing.JLabel();
        lbMaHH = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        txtMaHH = new javax.swing.JTextField();
        txtTenHH = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        txtDVT = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        BangDSHH = new javax.swing.JTable();
        btThem = new javax.swing.JButton();
        btLuu = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        btTim = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbSoLuong1 = new javax.swing.JLabel();
        txtMaLoai = new javax.swing.JTextField();
        btCapNhat = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        txtSearch.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        lbTenHH.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbTenHH.setText("Tên HH:");

        lbSoLuong.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbSoLuong.setText("Số Lượng:");

        lbDVT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbDVT.setText("DVT:");

        lbGia.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbGia.setText("Giá:");

        lbMaHH.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbMaHH.setText("Mã HH:");

        txtSoLuong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtMaHH.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtTenHH.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtGia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtDVT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        BangDSHH.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BangDSHH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        BangDSHH.setRowHeight(27);
        BangDSHH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BangDSHHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(BangDSHH);

        btThem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlbh/images/logoThem.png"))); // NOI18N
        btThem.setText("Thêm");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btLuu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlbh/images/logoLuu.png"))); // NOI18N
        btLuu.setText("Lưu");
        btLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLuuActionPerformed(evt);
            }
        });

        btXoa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlbh/images/logoXoa.png"))); // NOI18N
        btXoa.setText("Xóa");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        btTim.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlbh/images/logoTimKiem.png"))); // NOI18N
        btTim.setText("Tìm");
        btTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Nhập loại cần tìm:");

        lbSoLuong1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbSoLuong1.setText("Mã loại:");

        txtMaLoai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btCapNhat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlbh/images/logoCapNhat.png"))); // NOI18N
        btCapNhat.setText("Cập Nhật");
        btCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCapNhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btTim, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbMaHH, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTenHH, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSoLuong1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbGia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtDVT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaHH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTenHH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSoLuong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btCapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addGap(81, 81, 81)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(103, 103, 103))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(lbDVT, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 728, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtDVT, txtGia, txtMaHH, txtMaLoai, txtSoLuong, txtTenHH});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btCapNhat, btLuu, btThem, btXoa});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btTim, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbMaHH, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaHH, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTenHH, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenHH, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSoLuong1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDVT, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDVT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbGia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btThem, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                            .addComponent(btCapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtDVT, txtMaHH, txtMaLoai, txtTenHH});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        // TODO add your handling code here:
        txtMaHH.setText("");
        txtTenHH.setText("");
        txtMaLoai.setText("");
        txtSoLuong.setText("");
        txtDVT.setText("");
        txtGia.setText("");
        txtDVT.setEnabled(true);
        txtGia.setEnabled(true);
        txtMaHH.setEnabled(true);
        txtMaLoai.setEnabled(true);
        txtSoLuong.setEnabled(true);
        txtTenHH.setEnabled(true);
        btCapNhat.setEnabled(true);
        btLuu.setEnabled(true);
        txtMaHH.requestFocus(true);
    }//GEN-LAST:event_btThemActionPerformed

    private void BangDSHHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BangDSHHMouseClicked
        // TODO add your handling code here:
        int row = BangDSHH.getSelectedRow();
        txtMaHH.setText((String ) BangDSHH.getValueAt(row, 0));
        txtTenHH.setText((String) BangDSHH.getValueAt(row, 1));
        txtMaLoai.setText((String) BangDSHH.getValueAt(row, 2));
        txtSoLuong.setText((int) BangDSHH.getValueAt(row, 3)+"");
        txtDVT.setText((String) BangDSHH.getValueAt(row, 4));
        txtGia.setText((float) BangDSHH.getValueAt(row, 5)+"");
    }//GEN-LAST:event_BangDSHHMouseClicked

    private void btLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLuuActionPerformed
        // TODO add your handling code here:
        //nếu rỗng
        if(txtMaHH.getText().isEmpty()){
        JOptionPane.showMessageDialog(this, "Không được để mã số rỗng");
        txtMaHH.requestFocus();
        }
        else{
            String maHH = txtMaHH.getText();
            String tenHH = txtTenHH.getText();
            String maLoai = txtMaLoai.getText();
            int soLuong = Integer.parseInt(txtSoLuong.getText());
            String dVT = txtDVT.getText();
            float gia = Float.parseFloat(txtGia.getText());
            HangHoa hh = new HangHoa();
            hh.setMaHH(maHH);
            hh.setTenHH(tenHH);
            hh.setMaLoai(maLoai);
            hh.setSoLuong(soLuong);
            hh.setdVT(dVT);
            hh.setGia(gia);
            HangHoaDAO.themHangHoa(hh);
            JOptionPane.showMessageDialog(null, "Thêm thành công");
            hienThi();
        }
    }//GEN-LAST:event_btLuuActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        // TODO add your handling code here:
        if(BangDSHH.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(this, "Chọn dòng cần xóa");
            return;
        }
        int xoa = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không", "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (xoa == JOptionPane.YES_OPTION){
            try {
                String mahh = txtMaHH.getText();
                HangHoa cv = new HangHoa();
                cv.setMaHH(mahh);
                HangHoaDAO.xoaHangHoa(mahh);
                JOptionPane.showMessageDialog(null, "Xóa thành công");
                hienThi();
                txtDVT.setText("");
                txtGia.setText("");
                txtMaHH.setText("");
                txtMaLoai.setText("");
                txtSoLuong.setText("");
                txtTenHH.setText("");
            } catch (Exception e) {
                System.out.println("Không xóa được");
            }
        }  
    }//GEN-LAST:event_btXoaActionPerformed

    private void btTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimActionPerformed
        // TODO add your handling code here:
        hienThiTK();
        
    }//GEN-LAST:event_btTimActionPerformed

    private void btCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCapNhatActionPerformed
        // TODO add your handling code here:
        String mahh = txtMaHH.getText();
        String tenhh = txtTenHH.getText();
        String maLoai = txtMaLoai.getText();
        int soLuong = Integer.parseInt(txtSoLuong.getText());
        String dVT = txtDVT.getText();
        float gia = Float.parseFloat(txtGia.getText());
        HangHoa hh = new HangHoa(mahh, tenhh, maLoai, soLuong, dVT, gia);
        HangHoaDAO.capNhatHangHoa(hh);
        hienThi();
        JOptionPane.showMessageDialog(this, "Cập nhật thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btCapNhatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BangDSHH;
    private javax.swing.JButton btCapNhat;
    private javax.swing.JButton btLuu;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btTim;
    private javax.swing.JButton btXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbDVT;
    private javax.swing.JLabel lbGia;
    private javax.swing.JLabel lbMaHH;
    private javax.swing.JLabel lbSoLuong;
    private javax.swing.JLabel lbSoLuong1;
    private javax.swing.JLabel lbTenHH;
    private javax.swing.JTextField txtDVT;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMaHH;
    private javax.swing.JTextField txtMaLoai;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenHH;
    // End of variables declaration//GEN-END:variables

}
