/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlbh.view;

import java.util.ArrayList;
import java.util.List;
import qlbh.bean.DanhMuc;
import qlbh.control.ChuyenMangHinh;

/**
 *
 * @author DELL
 */
public class MainJFrame extends javax.swing.JFrame {

    public MainJFrame() {
        initComponents();
        setTitle("QUẢN LÍ BÁN HÀNG");
     
        ChuyenMangHinh controller = new ChuyenMangHinh(pnView);
        controller.setView(pnTC, lbTC);
        
        List<DanhMuc> listItem = new ArrayList<>();
        listItem.add(new DanhMuc("NhanVien", pnDSNV, lbDSNV));
        listItem.add(new DanhMuc("HangHoa", pnDSHH, lbDSHH));
        listItem.add(new DanhMuc("KhachHang", pnDSKH, lbDSKH));
        listItem.add(new DanhMuc("NhaCungCap", pnNCC, lbNCC));
        listItem.add(new DanhMuc("PhieuNhap", pnDSPN, lbDSPN));
        listItem.add(new DanhMuc("ChucVu", pnCV, lbCV));
        listItem.add(new DanhMuc("TrangChu", pnTC, lbTC));
        listItem.add(new DanhMuc("BanHang", pnBanHang, lbBanHang));

        controller.setEven(listItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnRoot = new javax.swing.JPanel();
        pnMenu = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnDSNV = new javax.swing.JPanel();
        lbDSNV = new javax.swing.JLabel();
        pnDSHH = new javax.swing.JPanel();
        lbDSHH = new javax.swing.JLabel();
        pnNCC = new javax.swing.JPanel();
        lbNCC = new javax.swing.JLabel();
        pnDSPN = new javax.swing.JPanel();
        lbDSPN = new javax.swing.JLabel();
        pnDSKH = new javax.swing.JPanel();
        lbDSKH = new javax.swing.JLabel();
        pnCV = new javax.swing.JPanel();
        lbCV = new javax.swing.JLabel();
        pnTC = new javax.swing.JPanel();
        lbTC = new javax.swing.JLabel();
        pnBanHang = new javax.swing.JPanel();
        lbBanHang = new javax.swing.JLabel();
        pnView = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        pnRoot.setBackground(new java.awt.Color(255, 255, 255));

        pnMenu.setBackground(new java.awt.Color(16, 16, 10));

        jPanel3.setBackground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlbh/images/logoBH.png"))); // NOI18N
        jLabel1.setText("QUẢN LÍ BÁN HÀNG");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pnDSNV.setBackground(new java.awt.Color(0, 102, 0));

        lbDSNV.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbDSNV.setForeground(new java.awt.Color(255, 255, 255));
        lbDSNV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDSNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlbh/images/logiNV.png"))); // NOI18N
        lbDSNV.setText("Danh Sách Nhân Viên");

        javax.swing.GroupLayout pnDSNVLayout = new javax.swing.GroupLayout(pnDSNV);
        pnDSNV.setLayout(pnDSNVLayout);
        pnDSNVLayout.setHorizontalGroup(
            pnDSNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDSNVLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbDSNV, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnDSNVLayout.setVerticalGroup(
            pnDSNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDSNVLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbDSNV)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pnDSHH.setBackground(new java.awt.Color(0, 102, 0));

        lbDSHH.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbDSHH.setForeground(new java.awt.Color(255, 255, 255));
        lbDSHH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDSHH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlbh/images/logoHH.png"))); // NOI18N
        lbDSHH.setText("Danh Sách Hàng Hóa");

        javax.swing.GroupLayout pnDSHHLayout = new javax.swing.GroupLayout(pnDSHH);
        pnDSHH.setLayout(pnDSHHLayout);
        pnDSHHLayout.setHorizontalGroup(
            pnDSHHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDSHHLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbDSHH, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnDSHHLayout.setVerticalGroup(
            pnDSHHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDSHHLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbDSHH)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pnNCC.setBackground(new java.awt.Color(0, 102, 0));

        lbNCC.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbNCC.setForeground(new java.awt.Color(255, 255, 255));
        lbNCC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlbh/images/logoNCC.png"))); // NOI18N
        lbNCC.setText("Nhà Cung Cấp");

        javax.swing.GroupLayout pnNCCLayout = new javax.swing.GroupLayout(pnNCC);
        pnNCC.setLayout(pnNCCLayout);
        pnNCCLayout.setHorizontalGroup(
            pnNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNCCLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnNCCLayout.setVerticalGroup(
            pnNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnNCCLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(lbNCC)
                .addGap(15, 15, 15))
        );

        pnDSPN.setBackground(new java.awt.Color(0, 102, 0));

        lbDSPN.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbDSPN.setForeground(new java.awt.Color(255, 255, 255));
        lbDSPN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDSPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlbh/images/logoPN.png"))); // NOI18N
        lbDSPN.setText("Danh Sách Phiếu Nhập");

        javax.swing.GroupLayout pnDSPNLayout = new javax.swing.GroupLayout(pnDSPN);
        pnDSPN.setLayout(pnDSPNLayout);
        pnDSPNLayout.setHorizontalGroup(
            pnDSPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDSPNLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbDSPN, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnDSPNLayout.setVerticalGroup(
            pnDSPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDSPNLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbDSPN)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pnDSKH.setBackground(new java.awt.Color(0, 102, 0));

        lbDSKH.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbDSKH.setForeground(new java.awt.Color(255, 255, 255));
        lbDSKH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDSKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlbh/images/logoKH.png"))); // NOI18N
        lbDSKH.setText("Danh Sách Khách Hàng");

        javax.swing.GroupLayout pnDSKHLayout = new javax.swing.GroupLayout(pnDSKH);
        pnDSKH.setLayout(pnDSKHLayout);
        pnDSKHLayout.setHorizontalGroup(
            pnDSKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDSKHLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbDSKH)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnDSKHLayout.setVerticalGroup(
            pnDSKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDSKHLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(lbDSKH)
                .addGap(15, 15, 15))
        );

        pnCV.setBackground(new java.awt.Color(0, 102, 0));

        lbCV.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbCV.setForeground(new java.awt.Color(255, 255, 255));
        lbCV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlbh/images/logoCV.png"))); // NOI18N
        lbCV.setText("Chức Vụ");

        javax.swing.GroupLayout pnCVLayout = new javax.swing.GroupLayout(pnCV);
        pnCV.setLayout(pnCVLayout);
        pnCVLayout.setHorizontalGroup(
            pnCVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCVLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbCV, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnCVLayout.setVerticalGroup(
            pnCVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCVLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbCV)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pnTC.setBackground(new java.awt.Color(0, 102, 0));

        lbTC.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbTC.setForeground(new java.awt.Color(255, 255, 255));
        lbTC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlbh/images/logoHome.png"))); // NOI18N
        lbTC.setText("Màng Hình Chính");

        javax.swing.GroupLayout pnTCLayout = new javax.swing.GroupLayout(pnTC);
        pnTC.setLayout(pnTCLayout);
        pnTCLayout.setHorizontalGroup(
            pnTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTCLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbTC, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnTCLayout.setVerticalGroup(
            pnTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTCLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbTC)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pnBanHang.setBackground(new java.awt.Color(0, 102, 0));

        lbBanHang.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbBanHang.setForeground(new java.awt.Color(255, 255, 255));
        lbBanHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlbh/images/banHang.png"))); // NOI18N
        lbBanHang.setText("Bán Hàng");

        javax.swing.GroupLayout pnBanHangLayout = new javax.swing.GroupLayout(pnBanHang);
        pnBanHang.setLayout(pnBanHangLayout);
        pnBanHangLayout.setHorizontalGroup(
            pnBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBanHangLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnBanHangLayout.setVerticalGroup(
            pnBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBanHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnMenuLayout = new javax.swing.GroupLayout(pnMenu);
        pnMenu.setLayout(pnMenuLayout);
        pnMenuLayout.setHorizontalGroup(
            pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnDSHH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnNCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnDSPN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnDSKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnCV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnDSNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnTC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnBanHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnMenuLayout.setVerticalGroup(
            pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(pnDSNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(pnDSHH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(pnDSKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(pnNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(pnDSPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(pnCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(pnTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(pnBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnViewLayout = new javax.swing.GroupLayout(pnView);
        pnView.setLayout(pnViewLayout);
        pnViewLayout.setHorizontalGroup(
            pnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 779, Short.MAX_VALUE)
        );
        pnViewLayout.setVerticalGroup(
            pnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnRootLayout = new javax.swing.GroupLayout(pnRoot);
        pnRoot.setLayout(pnRootLayout);
        pnRootLayout.setHorizontalGroup(
            pnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRootLayout.createSequentialGroup()
                .addComponent(pnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnRootLayout.setVerticalGroup(
            pnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbBanHang;
    private javax.swing.JLabel lbCV;
    private javax.swing.JLabel lbDSHH;
    private javax.swing.JLabel lbDSKH;
    private javax.swing.JLabel lbDSNV;
    private javax.swing.JLabel lbDSPN;
    private javax.swing.JLabel lbNCC;
    private javax.swing.JLabel lbTC;
    private javax.swing.JPanel pnBanHang;
    private javax.swing.JPanel pnCV;
    private javax.swing.JPanel pnDSHH;
    private javax.swing.JPanel pnDSKH;
    private javax.swing.JPanel pnDSNV;
    private javax.swing.JPanel pnDSPN;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JPanel pnNCC;
    private javax.swing.JPanel pnRoot;
    private javax.swing.JPanel pnTC;
    private javax.swing.JPanel pnView;
    // End of variables declaration//GEN-END:variables

}
